name: educompat
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  google_sign_in: ^6.2.1
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.5.3
  flutter_svg: ^2.0.10
  intl: ^0.20.2
  connectivity_plus: ^6.1.4
  package_info_plus: ^8.3.0
  lottie: ^3.3.1
  firebase_messaging: ^15.2.9
  flutter_local_notifications: ^19.3.0
  firebase_analytics: ^11.5.2
  http: ^1.4.0
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  mime: ^2.0.0
  webview_flutter: ^4.11.0
  cached_network_image: ^3.4.0
  firebase_storage: ^12.4.9
  chewie: ^1.11.3
  video_player: ^2.10.0
  flutter_pdfview: ^1.4.0+1
  youtube_player_flutter: ^9.0.4
  flutter_inappwebview: ^6.0.0
  razorpay_flutter: ^1.4.0
  firebase_crashlytics: ^4.3.9
  rxdart: ^0.28.0
  workmanager: ^0.7.0
  firebase_performance: ^0.10.1+9
  visibility_detector: ^0.4.0+2
  fluttertoast: ^8.2.12
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  firebase_app_check: ^0.3.2+9
  hive_flutter: ^1.1.0
  cloud_functions: ^5.6.1
  url_launcher: ^6.3.2
  timezone: ^0.10.1
  uuid: ^4.5.1
  version: ^3.0.2
  syncfusion_flutter_pdfviewer: ^30.2.6
  flutter_widget_from_html_core: ^0.16.1
  device_info_plus: ^11.5.0
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^10.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/authLogin/google/googleIcon-48.svg
    - assets/icons/authLogin/google/googleIcon-96.svg
    - assets/icons/authLogin/apple/apple-50.svg
    - assets/icons/authLogin/apple/apple-100.svg
    - assets/loading/loading.json
    - assets/images/SplashScreen.svg
    - assets/images/login.svg

